import type { FeedSource } from "@/types/news"

export type CatalogFeedSource = Required<Pick<FeedSource, "name" | "url" | "topic" | "slug" | "region" | "priority">>

export const VERIFIED_FEED_SOURCES: CatalogFeedSource[] = [
  { name: "Google News Business", topic: "business", slug: "business", url: "https://news.google.com/rss/headlines/section/topic/BUSINESS?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Business", topic: "business", slug: "business", url: "https://news.google.com/rss/search?q=reuters+business&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC Business", topic: "business", slug: "business", url: "https://feeds.bbci.co.uk/news/business/rss.xml", region: "uk", priority: 9 },
  { name: "CNBC Top News", topic: "business", slug: "business", url: "https://www.cnbc.com/id/100003114/device/rss/rss.html", region: "us", priority: 8 },
  { name: "CNBC Business", topic: "business", slug: "business", url: "https://www.cnbc.com/id/10001147/device/rss/rss.html", region: "us", priority: 8 },
  { name: "MarketWatch Top Stories", topic: "business", slug: "business", url: "https://feeds.marketwatch.com/marketwatch/topstories/", region: "us", priority: 7 },
  { name: "Bloomberg Markets", topic: "business", slug: "business", url: "https://feeds.bloomberg.com/markets/news.rss", region: "global", priority: 7 },
  { name: "Financial Times", topic: "business", slug: "business", url: "https://www.ft.com/rss/home", region: "global", priority: 6 },
  { name: "Google News Climate", topic: "climate", slug: "climate", url: "https://news.google.com/rss/search?q=climate+change&hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Environment", topic: "climate", slug: "climate", url: "https://news.google.com/rss/search?q=reuters+environment&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC Science Environment", topic: "climate", slug: "climate", url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", region: "uk", priority: 9 },
  { name: "The Guardian Environment", topic: "climate", slug: "climate", url: "https://www.theguardian.com/environment/rss", region: "global", priority: 8 },
  { name: "Google News NASA Climate", topic: "climate", slug: "climate", url: "https://news.google.com/rss/search?q=NASA+climate+news&hl=en&gl=US&ceid=US:en", region: "us", priority: 8 },
  { name: "Yale Climate Connections", topic: "climate", slug: "climate", url: "https://yaleclimateconnections.org/feed/", region: "us", priority: 7 },
  { name: "Carbon Brief", topic: "climate", slug: "climate", url: "https://www.carbonbrief.org/feed", region: "global", priority: 7 },
  { name: "Climate Home News", topic: "climate", slug: "climate", url: "https://www.climatechangenews.com/feed", region: "global", priority: 7 },
  { name: "Google News Health", topic: "health", slug: "health", url: "https://news.google.com/rss/headlines/section/topic/HEALTH?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Health", topic: "health", slug: "health", url: "https://news.google.com/rss/search?q=reuters+health&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC Health", topic: "health", slug: "health", url: "https://feeds.bbci.co.uk/news/health/rss.xml", region: "uk", priority: 9 },
  { name: "NPR Health", topic: "health", slug: "health", url: "https://feeds.npr.org/1128/rss.xml", region: "us", priority: 8 },
  { name: "Google News WHO Health", topic: "health", slug: "health", url: "https://news.google.com/rss/search?q=WHO+health+news&hl=en&gl=US&ceid=US:en", region: "us", priority: 8 },
  { name: "Google News Medical News Today", topic: "health", slug: "health", url: "https://news.google.com/rss/search?q=Medical+News+Today&hl=en&gl=US&ceid=US:en", region: "us", priority: 7 },
  { name: "Google News Harvard Health", topic: "health", slug: "health", url: "https://news.google.com/rss/search?q=Harvard+Health&hl=en&gl=US&ceid=US:en", region: "us", priority: 7 },
  { name: "NHS Digital", topic: "health", slug: "health", url: "https://digital.nhs.uk/feed/all-blog-feed.xml", region: "uk", priority: 6 },
  { name: "WHO News", topic: "health", slug: "health", url: "https://www.who.int/rss-feeds/news-english.xml", region: "global", priority: 8 },
  { name: "Healthline News", topic: "health", slug: "health", url: "https://www.healthline.com/rss/health-news", region: "global", priority: 7 },
  { name: "Google News India", topic: "india", slug: "india", url: "https://news.google.com/rss/headlines/section/geo/IN?hl=en-IN&gl=IN&ceid=IN:en", region: "india", priority: 10 },
  { name: "NDTV Top Stories", topic: "india", slug: "india", url: "https://feeds.feedburner.com/ndtvnews-top-stories", region: "india", priority: 9 },
  { name: "Times of India", topic: "india", slug: "india", url: "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", region: "india", priority: 9 },
  { name: "The Hindu", topic: "india", slug: "india", url: "https://www.thehindu.com/feeder/default.rss", region: "india", priority: 8 },
  { name: "Indian Express", topic: "india", slug: "india", url: "https://indianexpress.com/feed", region: "india", priority: 8 },
  { name: "Google News Politics", topic: "politics", slug: "politics", url: "https://news.google.com/rss/headlines/section/topic/NATION?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Politics", topic: "politics", slug: "politics", url: "https://news.google.com/rss/search?q=reuters+politics&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC Politics", topic: "politics", slug: "politics", url: "https://feeds.bbci.co.uk/news/politics/rss.xml", region: "uk", priority: 8 },
  { name: "The Hill", topic: "politics", slug: "politics", url: "https://thehill.com/feed/", region: "us", priority: 8 },
  { name: "NPR Politics", topic: "politics", slug: "politics", url: "https://feeds.npr.org/1014/rss.xml", region: "us", priority: 8 },
  { name: "Google News AP Politics", topic: "politics", slug: "politics", url: "https://news.google.com/rss/search?q=AP+politics&hl=en&gl=US&ceid=US:en", region: "us", priority: 7 },
  { name: "Politico", topic: "politics", slug: "politics", url: "https://rss.politico.com/politics-news.xml", region: "us", priority: 8 },
  { name: "Google News Science", topic: "science", slug: "science", url: "https://news.google.com/rss/headlines/section/topic/SCIENCE?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Science", topic: "science", slug: "science", url: "https://news.google.com/rss/search?q=reuters+science&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "NASA Breaking News", topic: "science", slug: "science", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", region: "us", priority: 9 },
  { name: "ScienceDaily All", topic: "science", slug: "science", url: "https://www.sciencedaily.com/rss/all.xml", region: "global", priority: 8 },
  { name: "ScienceDaily Top Science", topic: "science", slug: "science", url: "https://www.sciencedaily.com/rss/top/science.xml", region: "global", priority: 8 },
  { name: "Phys.org", topic: "science", slug: "science", url: "https://phys.org/rss-feed/", region: "global", priority: 8 },
  { name: "New Scientist", topic: "science", slug: "science", url: "https://www.newscientist.com/feed/home/", region: "global", priority: 7 },
  { name: "Nature News", topic: "science", slug: "science", url: "https://www.nature.com/nature.rss", region: "global", priority: 6 },
  { name: "NPR Science", topic: "science", slug: "science", url: "https://feeds.npr.org/1007/rss.xml", region: "us", priority: 7 },
  { name: "The Wire Science", topic: "science", slug: "science", url: "https://science.thewire.in/feed/", region: "india", priority: 7 },
  { name: "Google News Sports", topic: "sports", slug: "sports", url: "https://news.google.com/rss/headlines/section/topic/SPORTS?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters Sports", topic: "sports", slug: "sports", url: "https://news.google.com/rss/search?q=reuters+sports&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC Sport", topic: "sports", slug: "sports", url: "https://feeds.bbci.co.uk/sport/rss.xml", region: "uk", priority: 9 },
  { name: "CBS Sports", topic: "sports", slug: "sports", url: "https://www.cbssports.com/rss/headlines/", region: "us", priority: 8 },
  { name: "Sky Sports", topic: "sports", slug: "sports", url: "https://www.skysports.com/rss/12040", region: "uk", priority: 8 },
  { name: "Google News ESPN Sports", topic: "sports", slug: "sports", url: "https://news.google.com/rss/search?q=ESPN+sports+news&hl=en&gl=US&ceid=US:en", region: "us", priority: 7 },
  { name: "ESPN Top Headlines", topic: "sports", slug: "sports", url: "https://www.espn.com/espn/rss/news", region: "us", priority: 8 },
  { name: "Google News Technology", topic: "technology", slug: "technology", url: "https://news.google.com/rss/headlines/section/topic/TECHNOLOGY?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "The Verge", topic: "technology", slug: "technology", url: "https://www.theverge.com/rss/index.xml", region: "global", priority: 9 },
  { name: "TechCrunch", topic: "technology", slug: "technology", url: "https://techcrunch.com/feed/", region: "us", priority: 9 },
  { name: "Ars Technica", topic: "technology", slug: "technology", url: "https://feeds.arstechnica.com/arstechnica/index", region: "global", priority: 8 },
  { name: "Wired", topic: "technology", slug: "technology", url: "https://www.wired.com/feed/rss", region: "us", priority: 8 },
  { name: "MIT Technology Review", topic: "technology", slug: "technology", url: "https://www.technologyreview.com/feed/", region: "global", priority: 7 },
  { name: "Hacker News", topic: "technology", slug: "technology", url: "https://hnrss.org/frontpage", region: "global", priority: 7 },
  { name: "Hacker News RSS", topic: "technology", slug: "technology", url: "https://news.ycombinator.com/rss", region: "global", priority: 7 },
  { name: "VentureBeat", topic: "technology", slug: "technology", url: "https://venturebeat.com/feed/", region: "us", priority: 7 },
  { name: "Google News World", topic: "world", slug: "world", url: "https://news.google.com/rss/headlines/section/topic/WORLD?hl=en&gl=US&ceid=US:en", region: "us", priority: 10 },
  { name: "Google News Reuters World", topic: "world", slug: "world", url: "https://news.google.com/rss/search?q=reuters+world+news&hl=en&gl=US&ceid=US:en", region: "us", priority: 9 },
  { name: "BBC World", topic: "world", slug: "world", url: "https://feeds.bbci.co.uk/news/world/rss.xml", region: "uk", priority: 9 },
  { name: "Al Jazeera English", topic: "world", slug: "world", url: "https://www.aljazeera.com/xml/rss/all.xml", region: "middleeast", priority: 8 },
  { name: "Google News AP World", topic: "world", slug: "world", url: "https://news.google.com/rss/search?q=AP+world+news&hl=en&gl=US&ceid=US:en", region: "us", priority: 8 },
  { name: "Deutsche Welle", topic: "world", slug: "world", url: "https://rss.dw.com/xml/rss-en-all", region: "global", priority: 7 },
  { name: "France 24 English", topic: "world", slug: "world", url: "https://www.france24.com/en/rss", region: "global", priority: 7 },
  { name: "NPR World", topic: "world", slug: "world", url: "https://feeds.npr.org/1004/rss.xml", region: "us", priority: 7 },
  { name: "AP News", topic: "world", slug: "world", url: "https://openrss.org/feed/apnews.com/hub/ap-top-news", region: "us", priority: 8 },
  { name: "Reuters World", topic: "world", slug: "world", url: "https://openrss.org/feed/www.reuters.com/world/", region: "global", priority: 8 },
]
