"use client"

import { useState } from "react"

export default function DigestClient({
  initialDigest,
}: {
  initialDigest: string | null
}) {
  const [digest, setDigest] = useState<string | null>(initialDigest)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [regenerating, setRegenerating] = useState(false)

  async function generateDigest(regen = false) {
    if (regen) {
      setRegenerating(true)
      await fetch("/api/ai/digest", { method: "DELETE" })
    } else {
      setLoading(true)
    }
    setError(null)

    try {
      const res = await fetch("/api/ai/digest")
      const data = await res.json()
      if (!res.ok || data.error) {
        setError("AI service is unavailable right now. Try again when Ollama is running.")
      }
      else setDigest(data.digest)
    } catch (e) {
      setError(String(e))
    } finally {
      setLoading(false)
      setRegenerating(false)
    }
  }

  if (!digest && !loading) {
    return (
      <div style={{
        textAlign: "center",
        padding: "60px 0",
        border: "1px dashed var(--border)",
        borderRadius: 6,
      }}>
        <div style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 12,
          color: "var(--muted)",
          marginBottom: 20,
        }}>
          No digest generated yet for today
        </div>
        <button
          onClick={() => generateDigest(false)}
          style={{
            fontFamily: "'IBM Plex Mono', monospace",
            fontSize: 12,
            letterSpacing: "1px",
            textTransform: "uppercase",
            padding: "12px 32px",
            background: "var(--accent)",
            color: "#000",
            border: "none",
            borderRadius: 3,
            cursor: "pointer",
          }}
        >
          Generate Today&apos;s Digest
        </button>
        {error && (
          <div style={{
            marginTop: 16,
            fontFamily: "'IBM Plex Mono', monospace",
            fontSize: 11,
            color: "#ff4d4d",
          }}>
            {error}
          </div>
        )}
      </div>
    )
  }

  if (loading) {
    return (
      <div style={{
        textAlign: "center",
        padding: "60px 0",
        border: "1px dashed var(--border)",
        borderRadius: 6,
      }}>
        <div style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 12,
          color: "var(--accent)",
          marginBottom: 8,
        }}>
          AI is reading today&apos;s news...
        </div>
        <div style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 11,
          color: "var(--muted)",
        }}>
          This may take 20–40 seconds
        </div>
      </div>
    )
  }

  return (
    <div>
      <div style={{
        background: "var(--surface)",
        border: "1px solid var(--border)",
        borderRadius: 6,
        padding: "28px 32px",
        marginBottom: 20,
      }}>
        <div style={{
          fontFamily: "'IBM Plex Sans', sans-serif",
          fontSize: 15,
          lineHeight: 1.85,
          color: "var(--text)",
          whiteSpace: "pre-wrap",
        }}>
          {digest}
        </div>
      </div>

      <div style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      }}>
        <span style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 10,
          color: "var(--muted)",
          letterSpacing: "1px",
        }}>
          Generated by AI · Updates daily
        </span>
        <button
          onClick={() => generateDigest(true)}
          disabled={regenerating}
          style={{
            fontFamily: "'IBM Plex Mono', monospace",
            fontSize: 10,
            letterSpacing: "1px",
            textTransform: "uppercase",
            padding: "6px 16px",
            background: "transparent",
            color: regenerating ? "var(--muted)" : "var(--muted)",
            border: "1px solid var(--border)",
            borderRadius: 3,
            cursor: regenerating ? "not-allowed" : "pointer",
          }}
        >
          {regenerating ? "Regenerating..." : "Regenerate"}
        </button>
      </div>
    </div>
  )
}
